- name: Install kitty
  package:
    name:
      - keychain
      - kitty
    state: present
  become: yes

- name: Link config
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/dotfiles/.config/kitty'
    dest: '{{ ansible_env.HOME }}/.config/kitty'
    state: link
