- name: Install zsh
  package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: installed
  become: yes

- name: Change default shell to zsh
  become: yes
  shell: chsh -s /bin/zsh "{{ ansible_env.USER }}"
  changed_when: false

- name: Install powerlevel10 theme
  vars:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: $HOME/powerlevel10k
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    depth: 1
