- name: Install zsh
  package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: installed
  become: yes

- name: Change default shell to zsh
  become: yes
  shell: chsh -s /bin/zsh "{{ ansible_env.USER }}"
  changed_when: false

- name: Install powerlevel10 theme
  vars:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.local/share/zsh/plugins/zsh-theme-powerlevel10k"
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    depth: 1

- name: Install zsh-autosuggestions
  vars:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.local/share/zsh/plugins/zsh-autosuggestions"
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    depth: 1
