- name: Install neovim package
  package:
    name:
      - neovim
      - universal-ctags
      - xsel
    state: present
  become: yes

- name: Link config
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/dotfiles/.config/nvim'
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    state: link

- name: Symlink vim to nvim
  ansible.builtin.file:
    src: '/usr/bin/nvim'
    dest: '/usr/bin/vim'
    state: link
  become: yes
