- name: Install qtile and LightDM
  package:
    name:
      - qtile
      - xrandr
      - rofi
      - lightdm
      - light-locker
      - picom
      - dex
    state: installed
  become: yes

- name: Install relevant packages
  package:
    name:
      - playerctl
      - alsa-utils
      - blueman
      - qalculate-gtk
      - nomacs
      - scrot
      - psutil
      - nitrogen
      - numlockx
      - redshift
    state: installed
  become: yes

- name: Link qtile config
  shell: stow qtile --target "{{ ansible_env.HOME }}" --dir "{{ ansible_env.HOME }}/dotfiles"
  changed_when: false
