- name: Install fish
  package:
    name:
      - fish
    state: present
  become: yes

- name: Create config dir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/fish/'
    state: directory

- name: Link config
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/dotfiles/.config/fish/config.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/config.fish'
    state: link

# configuration
# install fisher to manage plugins and install tide to theme fish
