- name : Install stow
  package:
    name: stow
    state: installed
  become: yes
  tags:
    - dev
    - stow

- name: Symlink dotfiles using stow
  shell: stow --target='$HOME' --dir='$HOME/dotfiles'
