- name : Install stow
  package:
    name: stow
    state: installed
  become: yes

- name: Symlink dotfiles using stow
  vars:
    stow_target: "{{ ansible_env.HOME }}"
    stow_dir: "{{ stow_target }}/dotfiles"
  shell: stow . --target "{{ stow_target }}" --dir "{{ stow_dir }}"
  changed_when: false
