- name: deploy essential packges
  hosts: localhost
  gather_facts: yes
  roles:
    - role: alacritty
      tags:
        - alacritty
        - dev
    - role: zsh
      tags:
        - zsh
        - dev
    - role: tmux
      tags:
        - dev
        - tmux
    - role: neovim
      tags:
        - dev
        - neovim
    - role: stow
      tags: stow
    - role: doom-emacs
      tags: doom-emacs
    - role: qtile
      tags: qtile
