- name: deploy essential packges
  hosts: localhost
  gather_facts: yes
  roles:
    - role: kitty
      tags:
        - dev
        - kitty
    - role: fish
      tags:
        - dev
        - fish
    - role: neovim
      tags:
        - dev
        - neovim
    - role: doom-emacs
      tags: doom-emacs
    - role: im
      tags: im
#    - role: qtile
#      tags: qtile
#    - role: zsh
#      tags:
#        - zsh
#    - role: stow
#      tags: stow
